name: Checks
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Checks
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install --upgrade pip
    - run: pip install "black==22.3.0"  mypy==v0.931 flake8==4.0.1
    - run: black --diff --check $(git ls-files '*.py')
    - run: mypy --strict $(git ls-files '*.py')
